### ISSUE TITLE
Allow generate types from `gql` with typescript-server plugin

### ISSUE THREAD

**Issue by swcarlosrj** [dotansimha/graphql-code-generator#1054]
**Describe the feature**
Allow generate types from `gql` with typescript-server plugin. Currently you can generate them from 'String' types but it could be interesting to allow generate them from `gql` function (import { gql } from 'graphql-tag'), in this case you might take advantage of [plugins](https://marketplace.visualstudio.com/items?itemName=kumar-harsh.graphql-for-vscode) for highlighting, linting & prettifying .

Current: (It works!)
```
const typeDefs = `
  extend type Query {
    capsules(): [Capsule]
    capsule(capsule_serial: String!, id: Boolean): Capsule
  }
`
```

Proposal: (It doesn't work)
```
const typeDefs = gql`
  extend type Query {
    capsules(): [Capsule]
    capsule(capsule_serial: String!, id: Boolean): Capsule
  }
`
```

This throws `The Query definition is not executable.`

**Comment by tomitrescak** [comment]
Is gql supported at all? For me no queries are generated

**Comment by swcarlosrj** [comment]
@tomitrescak I don't think so or I don't know how to do that, that's why I've opened this issue as feature proposal 😃. Hopefully it could be taken into consideration because I've seen so far a lot of GraphQL Servers using this practice

**Comment by kamilkisiela** [comment]
#1059 should enable that

**Comment by swcarlosrj** [comment]
@kamilkisiela thanks, awesome work 💯

**Comment by dotansimha** [comment]
Fixed in 0.15.1

**Comment by swcarlosrj** [comment]
@dotansimha this still doesn't work for me, do I am missing something out?

**Environment:**
OS: macOS Mojave 10.14.2 (18C54)
Codegen: 0.15.2
Node: 10.10.0

**Additional context**
Current codegen.yml config:
```
schema: src/graphql/schema/index.ts
documents: src/graphql/schema/**/*.ts
overwrite: true
watch: true
require:
  - ts-node/register
generates:
  ./src/graphql/types/types.d.ts:
    config:
      contextType: ./context#MyContext
    plugins:
      - typescript-common
      - typescript-server
      - typescript-resolvers
```

**Comment by kamilkisiela** [comment]
@swcarlosrj Why do you have `documents`? Do you use `typescript-client` package or related?

**Comment by swcarlosrj** [comment]
@kamilkisiela I was using it to allow generate types & 'watching' because `documents: src/graphql/schema/**/*.ts` doesn't generate the types correctly.

Using this conf, it seems to be watching but doesn't generate anything (I think because it's not possible by now)
```
schema: src/graphql/schema/**/*.ts
overwrite: true
watch: true
require:
  - ts-node/register
generates:
  ./src/graphql/types/types.d.ts:
    config:
      contextType: ./context#MyContext
    plugins:
      - typescript-common
      - typescript-server
      - typescript-resolvers
```

**Comment by swcarlosrj** [comment]
@kamilkisiela I've removed it (`documents`) and it's working properly! Apologies for disturbing 😅

**Comment by kamilkisiela** [comment]
@swcarlosrj You're not alone that uses `documents` this way. @dotansimha maybe we could improve docs or something?
