### ISSUE TITLE
v8 error: Cannot read property 'type' of undefined

### ISSUE THREAD

**Issue by altschuler** [dotansimha/graphql-code-generator#127]
Getting the following error after upgrading to v8.0.2. Not sure if I should have migrated something somehow?

```
$ $(yarn bin)/gql-gen -u http://localhost:3000/graphql -t typescript -o src/app/data/schema.ts "src/**/*.{queries,fragments}.ts"
Loading GraphQL Introspection from remote: http://localhost:3000/graphql...
TypeError: Cannot read property 'type' of undefined
    at /home/simon/dev/plotist/plotist-ng/node_modules/graphql-codegen-core/dist/operations/build-selection-set.js:37:64
    at Array.map (native)
    at Object.buildSelectionSet (/home/simon/dev/plotist/plotist-ng/node_modules/graphql-codegen-core/dist/operations/build-selection-set.js:31:61)
    at Object.transformFragment (/home/simon/dev/plotist/plotist-ng/node_modules/graphql-codegen-core/dist/operations/transform-fragment-document.js:17:45)
    at /home/simon/dev/plotist/plotist-ng/node_modules/graphql-codegen-core/dist/operations/transform-document.js:21:65
    at Array.forEach (native)
    at transformDocument (/home/simon/dev/plotist/plotist-ng/node_modules/graphql-codegen-core/dist/operations/transform-document.js:16:17)
    at Object.<anonymous> (/home/simon/dev/plotist/plotist-ng/node_modules/graphql-code-generator/dist/cli.js:138:43)
    at step (/home/simon/dev/plotist/plotist-ng/node_modules/graphql-code-generator/dist/cli.js:32:23)
    at Object.next (/home/simon/dev/plotist/plotist-ng/node_modules/graphql-code-generator/dist/cli.js:13:53)
```

**Comment by dotansimha** [comment]
@altschuler can you execute with `DEBUG=true gql-gen ...` and share the output? :) 

Also, I noticed a minor but with the output file (you should specify only a directory at the moment, because the generator append the `types.d.ts` always - i will fix it really soon).

**Comment by altschuler** [comment]
That's a pretty long output, so here's a paste https://pastebin.com/aw8dp9Nk

**Comment by dotansimha** [comment]
It looks like something with the `ChapterWordCount` fragment. Probably just an end case I didn't cover in tests and implementation. can you please share the definition of the fragment? 

Thanks :)

**Comment by altschuler** [comment]
```
fragment ChapterWordCount on Chapter {
    __typename
    id
    wordCount
}
```

**Comment by dotansimha** [comment]
Thank you!
I can guess that it's something about the __typename, let me check and I'll update soon.

**Comment by altschuler** [comment]
Awesome, thanks! I noticed that the `getFieldDef` util function uses `parentType.getFields()` which only returns the defined fields of the type. Since `__typename` isn't an actually defined field it might be a special case to consider?

**Comment by altschuler** [comment]
Yeah, so doing the following makes it emit properly. It's not how it should be fixed, but FWIW I'll add it here

```
function getFieldDef(parentType, fieldAST) {
    var name = fieldAST.name.value;

    if (name === '__typename') {
        return  {
            description: '',
            deprecationReason: null,
            type: new graphql_1.GraphQLNonNull(graphql_1.GraphQLString),
            args: [],
            isDeprecated: false,
            name: '__typename',
        };
    }
    ...
```

**Comment by altschuler** [comment]
A few more notes:
- It's emitting some seemingly "raw" graphql types, such as `ID` and `Int` which are not aliased. I guess there're some type definitions missing in the header, such as `export type ID = string;`
- Nested fragment spreads are not getting emitted, resulting in syntax errors, eg:
```
export namespace FullWorld {
    export type Fragment = {
    :  | null;
    :  | null;
    summary: string;
}
}
```

and the definitions of this fragment is

```
fragment FullWorld on World {
    ...WorldCard
    ...WorldCounts
    summary
}
```

**Comment by dotansimha** [comment]
@altschuler, actually I guess that we need to ignore `__typename` as a field, because it's not relevant to the generation of the fragment (it's the same as the name of the type, and there is a field called `schemaBaseType` with this value).

I fixed it and release `graphql-code-generator@0.8.3`, can you please try it and update?

**Comment by dotansimha** [comment]
And regarding the issue with the output file, I opened an issue and I will fix it soon: https://github.com/dotansimha/graphql-code-generator/issues/128

**Comment by altschuler** [comment]
Very good point, it should be ignored yes! 0.8.3 solves the typename (fragment spread and wrong scalar types is still present). Thank you very much for you work on this, the new version is looking really cool!

**Comment by altschuler** [comment]
Btw, the missing fragment spreads in the above example should be emitted as (I suppose) 

```
export namespace FullWorld {
    export type Fragment = {
        summary: string;
    } & WorldCard.Fragment & WorldCounts.Fragment;
}
```

**Comment by dotansimha** [comment]
@altschuler can you please try `0.8.4` ? it should fix all those issues, including https://github.com/dotansimha/graphql-code-generator/issues/128. Thanks! :)

**Comment by altschuler** [comment]
Awesome, it works! The default emit templates (at least for typescript) are quite different than in 0.7, eg. `ElementsQuery.Result` is now emitted as `Elements.Query` so you might want to bump a major version?

**Comment by dotansimha** [comment]
@altschuler yeah that is my goal for the next days - just want to make sure that we don't have any other surprises like these issues :) 

Thank you so much for your review and help in fixing these issues!
