### ISSUE TITLE
Add support for __typename field

### ISSUE THREAD

**Issue by kvnvelasco** [dotansimha/graphql-code-generator#151]
I've looked over the codebase and i'm not entirely sure where to handle the case where the '__typename' field in a document maps to a `GraphQLObjectType | GraphQLObjectInputType`.

At some point in core or compiler this case has to be handled.

So far, i've explored only one implementation: hardcoding the __typename case into `transformGraphQLObject`.

There's probably an issue with converting a string literal type to whatever template we'll use later.

Can anyone lend some insight into a potential implementation for this? 

for typescript, it should output a type as follows 

```ts
namespace User {
  type Query = {
    user {
      id: number,
      __typename: "User"
    }

  }

}
```

for a query 
```gql
query User() {
  user {
    id
    __typename
  }
}
```

**Comment by dotansimha** [comment]
Currently we are removing this field. @kvnvelasco do you think we need to add it back? do you have an example for usage for this field?

**Comment by rasdaniil** [comment]
this would be the use case I think
https://github.com/dotansimha/graphql-code-generator/issues/166
otherwise how to distinguish between two inline fragments
Thanks!

**Comment by jonaskello** [comment]
I have what I think is a common use-case for the __typename field. Apollo requires that you specify the __typename field when doing optimistic updates. Since the generated types excludes the __typename field they are not useful for specifying the input for optimistic updates. See the [apollo docs](https://www.apollographql.com/docs/react/features/optimistic-ui.html#optimistic-basics) for an example.

I would suggest that the __typename field is included as an optional field in all types.

**Comment by tremby** [comment]
I have a field which gives an array of items which could be any of a bunch of different types. I need different behaviour for each one, and as far as I know the only way I can reliably distinguish between them is to look at `__typename`.

**Comment by dotansimha** [comment]
I'm thinking about it now. It might look simple but it does not... 
We also need to consider the cases of inline fragment and fragment spread that effects the `__typename` and it's possible values.

**Comment by dotansimha** [comment]
Fixed in 0.8.17 :)

**Comment by tremby** [comment]
I updated to 0.9.19 and still don't see `__typename` available, after restarting my development server and running the code generator again.

I'm using Gatsby and have the following script in my package.json: `"graphql-types": "gql-gen --url http://localhost:8000/___graphql --template typescript --out src/typings/graphql.d.ts",`. `__typename` doesn't appear anywhere in the output. Am I doing something wrong, or might this be an upstream Gatsby issue?

**Comment by dotansimha** [comment]
@tremby 
The discussion here talked mostly about Apollo, so I guessed that adding `__typename` was relevant only for client side usage, so I added `__typename` for the generated output of the GraphQL documents (queries, mutations, fragments) and not for the schema definition.

Can you please elaborate on your use case? maybe it's also relevant for the server side and I missed it. 

Thanks!

**Comment by tremby** [comment]
Apollo was only mentioned in one comment in the middle of this thread.

I'm using Gatsby, which is a static site generator but which allows your data sources to be queried at build time with GraphQL. The relevant data source for me is Contentful.

I have some fields in my data model which allow multiple references to other documents to be chosen, and they can be any of a number of different types. (This is for a "flexible content" layout -- plain text chunk, then recent posts chunk, then newsletter signup chunk, then more plain text, for example.) So I fetch these in a query, then when rendering I loop through them and need to know which type each chunk is to render it properly. So I'm looking at `__typename`, which does exist but TSLint isn't happy since the typings (produced by graphql-code-generator) don't list `__typename` as a field which exists.

**Comment by dotansimha** [comment]
@tremby I see. But if you are executing a Query to get the data, you can generate typings that are specific to your Queries. This way you can also get types for the specific selection set that your query needs. Have you tried it?

**Comment by tremby** [comment]
I'm not sure I can split out queries to their own files with Gatsby. I don't think I'd want to. Besides, it seems like a pain to regenerate the typings every time I change a query. There must be something I'm missing -- if it's an available field, why would you not mention its presence in the typings?

**Comment by dotansimha** [comment]
@tremby I'm not familiar with that way that Gatsby use GraphQL Queries. Any chance you can share an code example (maybe a repo)? 
This way we can find the best way to change the codegen and support your use case :)

**Comment by tremby** [comment]
Sure, you can start a basic Gatsby project with Typescript by following the [getting started docs](https://www.gatsbyjs.org/docs/) and at step 1 using a Typescript starter such as https://github.com/fabien0102/gatsby-starter (which is set up to use graphql-code-generator), like this: `gatsby new gatsby-site https://github.com/fabien0102/gatsby-starter`. Once that's done you can run `npm run graphql-types` to run graphql-code-generator.

**Comment by simPod** [comment]
I have the same issue, trying split rendering logic for types with common interface. I'd like to switch conditional branches based on `__typename` value

**Comment by dotansimha** [comment]
@simPod we fixed this issue in the recent refactor, it will be available very soon in 1.0.0.

**Comment by simPod** [comment]
@dotansimha looking forward, thanks for update!
