### ISSUE TITLE
Merge --url, --export, --file into a single flag (--schema)

### ISSUE THREAD

**Issue by dotansimha** [dotansimha/graphql-code-generator#202]
Discussed here: https://github.com/dotansimha/graphql-code-generator/pull/177#issuecomment-373277277

**Comment by anilanar** [comment]
My project needs to to generate code based on a function that returns `Promise<GraphQLSchema>`. Thus non of the existing options work for that use case and the only way is to fork/rewrite codegen-cli.

I was thinking of introducing a `--schema-loader` option.

**Comment by jonaskello** [comment]
I think maybe the current `--export` option could support `Promise<GraphQLSchema>`. It could check if the exported result is a Promise and then resolve it, otherwise just use it as-is.

**Comment by dotansimha** [comment]
Done in 0.9.0 :)

**Comment by jonaskello** [comment]
Nice work!

Perhaps the [usage section](https://github.com/dotansimha/graphql-code-generator#usage-examples) of the README needs to be updated to reflect these changes? It is still showing examples like this one:

```
gql-gen --file mySchema.json --template graphql-codege   .....
```
