### ISSUE TITLE
import-types-preset with react-apollo

### ISSUE THREAD

**Issue by xiaoyu-tamu** [dotansimha/graphql-code-generator#2742]
**Describe the bug**
 
![image](https://user-images.githubusercontent.com/33362998/66709863-1c45e080-ed32-11e9-83f9-c25282ee339a.png)

**To Reproduce**

1. My GraphQL schema:

```graphql
# Put your schema here
```

2. My GraphQL operations:

```graphql
fragment user on users {
  id
  username
  password
  is_active
  first_name
  last_name
  level
  type
  roles {
    is_default
    role {
      id
      name
    }
  }
}

query selectUsersByUsername($username: String!) {
  users(limit: 1, where: { username: { _eq: $username } }) {
    ...user
  }
}
 
```

3. My `codegen.yml` config file:
```yml
overwrite: true
strict: true
config:
  skipTypename: true
  namingConvention:
    typeNames: change-case#pascalCase
    transformUnderscore: true
  scalars:
    uuid: string
    timestamptz: string
schema:
  - some-remote-schema
generates:
  src/generated/types.ts:
    - typescript
  src/generated/api.ts:
    documents: documents/api/*.graphql
    preset: import-types
    presetConfig:
      typesPath: "@/generated/types.ts"
    plugins:
      - typescript-operations
      - typescript-graphql-request
  src/generated/www.tsx:
    documents: documents/www/*.graphql
    preset: import-types
    presetConfig:
      typesPath: "@/generated/types.ts"
    config:
      withHooks: true
      withHOC: false
      withComponent: false
    plugins:
      - typescript-operations
      - typescript-react-apollo
```

**Expected behavior**

Generated react-hook helpers should not prefix with Types.
**Environment:**

- OS: 
- `@graphql-codegen/...`: 
- NodeJS: 

**Additional context**

```
    "@graphql-codegen/cli": "1.8.1",
    "@graphql-codegen/typescript": "1.8.1",
    "@graphql-codegen/typescript-graphql-request": "1.8.1",
    "@graphql-codegen/typescript-operations": "1.8.1",
    "@graphql-codegen/typescript-react-apollo": "1.8.1",
```

**Comment by myylow** [comment]
I have the same, and a workaround is to split `typescript-react-apollo` away from `typescript-operations`. A structure something like this...

```
   src/generated/graphql-types.ts:
      - typescript

   src/generated/operation-types.tsx:
      preset: import-types
      presetConfig:
         typesPath: './graphql-types'
      plugins:
         - typescript-operations

   src/generated/apollo-types.tsx:
      preset: import-types
      presetConfig:
         typesPath: './operation-types'
      plugins:
         - typescript-react-apollo
```

**Comment by xiaoyu-tamu** [comment]
The issue still exist after 1.8.2 and the dot between Types and Query name disappeared

![image](https://user-images.githubusercontent.com/33362998/67498880-cdf3e400-f645-11e9-8478-525e56122b89.png)

**Comment by xiaoyu-tamu** [comment]
https://github.com/dotansimha/graphql-code-generator/blob/4529aae3277b5cc7c0f7c4d19f4b4769c0710381/packages/plugins/typescript/react-apollo/src/visitor.ts#L288-L296
```
    operationResultType = this.convertName(operationResultType, {
      prefix: this._prefix,
      useTypesPrefix: false,
    });

    operationVariablesTypes = this.convertName(operationVariablesTypes, {
      prefix: this._prefix,
      useTypesPrefix: false,
    });
```

The name before convert are correct. Looks like something wrong with convertName method, maybe caused by PR: Fixes for transformUnderscore (#2743)?

**Comment by dotansimha** [comment]
I think I managed to reproduce and fix this in: https://github.com/dotansimha/graphql-code-generator/pull/2862 


@xiaoyu-tamu Can you please try this alpha? `1.8.3-alpha-57c54418.34`

**Comment by xiaoyu-tamu** [comment]
@dotansimha it works. Thank you

**Comment by dotansimha** [comment]
Fixed in 1.8.3

**Comment by calumpeak** [comment]
@dotansimha I've upgraded to the most recent version and I'm still seeing this issue, have I made a mistake with my config by any chance? 

```yml
schema: http://localhost:3000/graphql
documents: ./src/**/*.{ts,tsx}
overwrite: true
hooks:
  afterAllFileWrite:
    - prettier --write
generates:
  ./src/@types/api/index.d.ts:
    plugins:
      - add: '/* eslint-disable */'
      - typescript
  ./src/hooks/apollo.ts:
    preset: import-types
    presetConfig:
      typesPath: ../@types/api/index.d
    plugins:
      - typescript-operations
      - typescript-react-apollo
    config:
      reactApolloVersion: 3
      withHooks: true
      withHOC: false
      withComponent: false
```

![image](https://user-images.githubusercontent.com/10559737/68299447-9cdad100-0093-11ea-99cd-e954eb16512d.png)

**Comment by ardatan** [comment]
@calumpeak Could you create a reproduction using codesandbox by any chance?

**Comment by calumpeak** [comment]
@ardatan Sure thing, here you go: https://codesandbox.io/s/unruffled-goldwasser-hurx5

If you run "yarn generateTypes" from the terminal you should be good (though I've generated them already)

**Comment by Urigo** [comment]
@calumpeak does that issue still happens on latest?

If so, could you open a new issue please?

**Comment by calumpeak** [comment]
@Urigo I will upgrade and test and get back to you. Thanks

**Comment by dmitrif** [comment]
Still happening (`Types.*` issue) on `^1.20.0`

**Comment by dotansimha** [comment]
@dmitrif can you please share a reproduction?

**Comment by adrianrivers** [comment]
@myylow your solution worked well for me, thanks :)
