### ISSUE TITLE
Unable to extend undefined GraphQL union

### ISSUE THREAD

**Issue by veeramarni** [dotansimha/graphql-code-generator#2926]
**Describe the bug**
 
When having `union` type in one schema and `extend union` of the same type in a different file, we get the following error. 

If we  put the `extend union` into the same file as `Schema1`, we don't get the error. It fails with `graphql-code-generator` when generating types.

**To Reproduce**

Schema1
```

  type Query {
    fooBar: [FooBar!]!
  }

  union FooBar = Foo | Bar

  type Foo {
    id: ID!
  }

  type Bar {
    id: ID!
  }

```

Schema2

```
  extend union FooBar = Zoo

  type Zoo {
    id: ID!
  }
```

Error
```
Failed to load schema from ./packages/graphql/**/*.graphql:

        Unable to extend undefined GraphQL union: [object Object]
        Error: Unable to extend undefined GraphQL union: [object Object]
```

1. My GraphQL schema:

```graphql
# Put your schema here
```

2. My GraphQL operations:

```graphql
# Put your operations here
```

3. My `codegen.yml` config file:

```yml
# Put your YML here
```

**Expected behavior**

No errors
**Environment:**

- OS: 
- `@graphql-codegen/...`: 1.8.3
- NodeJS: 

**Additional context**

**Comment by ardatan** [comment]
Hi @veeramarni 
Could you try with the following canary version?
`1.8.4-alpha-9451dd15.38+9451dd15`

**Comment by veeramarni** [comment]
@ardatan that fixes. @dotansimha, when we can get this, be published?

**Comment by veeramarni** [comment]
@dotansimha Any eta when this will be released?

**Comment by dotansimha** [comment]
Fixed in 1.9.0

**Comment by ArnaudBarre** [comment]
Sadly when using CLI I still get version 0.6 of graphql-toolkit because of graphql-config. I use yarn resolutions as a temporary solution

**Comment by dotansimha** [comment]
@ArnaudBarre It should be fixed now, all versions should be aligned. Let me know if it's still happens.

**Comment by ArnaudBarre** [comment]
I got an error in 1.12.1 (will open an issue if I have time). But 1.11 is 👌

**Comment by dotansimha** [comment]
@ArnaudBarre Can you please try latest version? If it doesn't work for you, can you please open a new issue with a reproduction?
