### ISSUE TITLE
[typescript-operations] Missing typings

### ISSUE THREAD

**Issue by alexkirsz** [dotansimha/graphql-code-generator#3090]
**Describe the bug**

When importing the `@graphql-codegen/typescript-operations` module with `ts-node`, I'm getting the following error:
```
 error TS7016: Could not find a declaration file for module '@graphql-codegen/typescript-operations'. '/project/node_modules/@graphql-codegen/typescript-operations/index.cjs.js' implicitly has an 'any' type.
  Try `npm install @types/graphql-codegen__typescript-operations` if it exists or add a new declaration (.d.ts) file containing `declare module '@graphql-codegen/typescript-operations';`

21 import * as tsOpPlugin from '@graphql-codegen/typescript-operations';
```

It looks like the `typings.d.ts` file referred to in the `package.json` of the module is not properly generated.

**To Reproduce**

Example sandbox:
https://codesandbox.io/s/vibrant-brahmagupta-w2pxy?fontsize=14&hidenavigation=1&theme=dark

You can see that the `@graphql-codegen/typescript-operations` module is not found, contrary to the `@graphql-codegen/typescript` module which is correctly found.

**Environment:**

- `@graphql-codegen/typescript-operations`: 1.9.1
- NodeJS: ts-node 8.5.4

**Comment by dotansimha** [comment]
You are right, @alexkirsz , the `typings` and `typescript` keys are missing in `package.json` while building the bundled artifact. 
@kamilkisiela I think this issue is related to `bob`, can you please take a look?

**Comment by dotansimha** [comment]
Fixed by @kamilkisiela and @ardatan in `bob` :)

**Comment by dotansimha** [comment]
Fixed in `v1.10.0`.

**Comment by esamattis** [comment]
It seems that the types are in the wrong path in `1.11.2`.

The `package.json` points to the package root
https://unpkg.com/browse/@graphql-codegen/typescript-operations@1.11.2/package.json

![image](https://user-images.githubusercontent.com/225712/72728097-3e52c880-3b95-11ea-8efa-a617864c2c89.png)

But the definitions seem to be in `operations/src/`

https://unpkg.com/browse/@graphql-codegen/typescript-operations@1.11.2/operations/src/


This workaround made it work for me:

```
cp node_modules/@graphql-codegen/typescript-operations/operations/src/*.d.ts node_modules/@graphql-codegen/typescript-operations
```

**Comment by alexkirsz** [comment]
@dotansimha I can confirm this is still an issue on the latest version of `@graphql-codegen/typescript-operations` (1.11.2)

**Comment by dotansimha** [comment]
Found the cause for this. Working on a fix.

**Comment by dotansimha** [comment]
Fixed in: https://github.com/dotansimha/graphql-code-generator/pull/3404

**Comment by dotansimha** [comment]
Fixed in `v1.12.0`
