### ISSUE TITLE
Schema won't generate with versions after 1.9.1

### ISSUE THREAD

**Issue by SoyYoRafa** [dotansimha/graphql-code-generator#3282]
**Describe the bug**
Hi,
The attached package can generate with 1.9.1 but not with 1.10.x nor 1.11.x. Type `Action` is in the imports of `src/service_b/Alert.graphql` so it should be able to find it. Separetely, it would be great it graphql-code-generator could log which file has the issue for readability purposes.

[graphql-codegen-bug-reproduce.tar.gz](https://github.com/dotansimha/graphql-code-generator/files/4051821/graphql-codegen-bug-reproduce.tar.gz)

```
  ✖ src/types.ts
    Failed to load schema from src/**/schema.graphql:

        Field suggestedActions: Couldn't find type Action in any of the schemas.
        Error: Field suggestedActions: Couldn't find type Action in any of the schemas.
    at collectNode (/Users/rafael/Downloads/graphql-codegen-bug-reproduce/node_modules/@graphql-toolkit/core/index.cjs.js:192:23)
    at newDefinition.fields.forEach.field (/Users/rafael/Downloads/graphql-codegen-bug-reproduce/node_modules/@graphql-toolkit/core/index.
cjs.js:140:13)
    at Array.forEach (<anonymous>)
    at collectNewTypeDefinitions (/Users/rafael/Downloads/graphql-codegen-bug-reproduce/node_modules/@graphql-toolkit/core/index.cjs.js:13
9:30)
    at completeDefinitionPool (/Users/rafael/Downloads/graphql-codegen-bug-reproduce/node_modules/@graphql-toolkit/core/index.cjs.js:80:43
)
    at processImportSyntax (/Users/rafael/Downloads/graphql-codegen-bug-reproduce/node_modules/@graphql-toolkit/core/index.cjs.js:310:28)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**To Reproduce**
```bash
tar xvf graphql-codegen-bug-reproduce.tar.gz
cd graphql-codegen-bug-reproduce
npm i
npm run build # works
sed -i "s|1.9.1|1.11.2|g" package.json
npm i
npm run build
```

1. My GraphQL schema:

Attached in package.

2. My GraphQL operations:

We have operations but we removed them from the uploaded package

3. My `codegen.yml` config file:

Attached in package.

**Expected behavior**
Generates file in src/types.ts

**Environment:**

- OS: Linux & Mac
- `@graphql-codegen/...`: 1.9.1-1.11.2
- NodeJS: 10

**Comment by dotansimha** [comment]
Fixed in: https://github.com/ardatan/graphql-toolkit/pull/445 , thanks @ardatan 
We updated to latest toolkit and released it in `v1.12.0`.

**Comment by SoyYoRafa** [comment]
Our scheme/documents still won't generate in 1.12.1. I am getting an AggregateError. "Cannot query field ... on type Mutation.". Documents can't seem to find the schema.

**Comment by ardatan** [comment]
That looks different kind of error. Please open another issue with a reproduction.

**Comment by MincePie** [comment]
@SoyYoRafa did you figure this out? I can't get the generator to run. The error message I get is 
AggregateError: GraphQL Document Validation failed with 1 errors;
      Error 0: GraphQLDocumentError: Cannot query field "logout" on type "Mutation".
