### ISSUE TITLE
typescript-resolvers' `mappers` config default aliasing not using alias

### ISSUE THREAD

**Issue by MartijnHols** [dotansimha/graphql-code-generator#3466]
**Describe the bug**
The `mappers` property of the `typescript-resolvers` plugin isn't using the alias name for imports, but instead using the field name.

**To Reproduce**

Given this plugin config:

```
      - typescript-resolvers:
          mappers:
            Account: ./models/Account#default as AccountModel
```

Returns this output:

```
import { default as Account } from './models/Account';
```

**Expected ~~behavior~~ output**
```
import AccountModel from './models/Account';
```

**Environment:**

- `@graphql-codegen/...`: 1.12.1

**Additional context**
Aliasing appears to be [undocumented](https://graphql-code-generator.com/docs/plugins/typescript-resolvers#mappers-object) but I found it in #2932.

I think the issue is caused by https://github.com/dotansimha/graphql-code-generator/blame/87c18582d6b76093e3c1f1254eb67734d8b454b9/packages/plugins/other/visitor-plugin-common/src/mappers.ts#L38, introduced in #3189.  I think this could be fixed by making `namedDefault` a separate conditional, like so:

```ts
      const namedDefault = items[1].includes('default as');
      asDefault = items[1] === 'default' || namedDefault;
      if (namedDefault) {
        const [, aliasType] = items[1].split(' as ');
        type = aliasType
        importElement = aliasType
      } else if (asDefault) {
        type = `${gqlTypeName}`;
        importElement = `${gqlTypeName}`;
      } else {
        if (items[1].includes(' as ')) {
          const [importedType, aliasType] = items[1].split(' as ');
          type = aliasType;
          importElement = `${importedType} as ${aliasType}`;
        } else {
          type = items[1];
          importElement = items[1];
        }
      }
```

**Comment by MartijnHols** [comment]
Found a workaround for the time being:

```ts
      - typescript-resolvers:
          mappers:
            Account: ./models/Account#default  as AccountModel
```

(two spaces before the `as`)

**Comment by dotansimha** [comment]
@kamilkisiela can you please take a look? :)

**Comment by kamilkisiela** [comment]
Why is `import { default as Foo } from './models'` bad since it's the same as `import Foo from './models`? It's a generated file so why does it matter, what's your use case?

**Comment by MartijnHols** [comment]
The issue is that it doesn't use the alias. Even if it uses the `import { default as Account } from './models/Account';` variation, it should still be `AccountModel` and not `Account`.

**Comment by kamilkisiela** [comment]
Ohh I see!

**Comment by kamilkisiela** [comment]
https://github.com/dotansimha/graphql-code-generator/pull/3498 should fix it

**Comment by schmod** [comment]
@kamilkisiela I'm still encountering the issue in the alpha version.  

```yml
  mapperTypeSuffix: Model
  mappers:
    Company: "../api/models/company.model#default as CompanyModel"
    Person: "../api/models/person.model#default"
```

yields this code:
```ts
import { default as Company } from '../api/models/company.model';
import Person from '../api/models/person.model'; // conflict
```

**Comment by kamilkisiela** [comment]
@dotansimha @schmod https://github.com/dotansimha/graphql-code-generator/pull/3601

The `mapperTypeSuffix` was broken even before my PR, now it should be fine.

**Comment by dotansimha** [comment]
Fixed in `v1.13.0`

**Comment by schmod** [comment]
Can confirm that both issues are fixed in `1.13.0`.  

Thank you so much for the attention to detail that you've given this project!
