### ISSUE TITLE
FragmentDoc imports are still broken in 1.12.2

### ISSUE THREAD

**Issue by mjbcopland** [dotansimha/graphql-code-generator#3525]
Related to #3259. 

[`config.documentMode !== 'documentNode' || config.documentMode !== 'external'`](https://github.com/dotansimha/graphql-code-generator/blob/v1.12.2/packages/presets/near-operation-file/src/fragment-resolver.ts#L21) introduced in #3436 always evaluates to `true`. This causes codegen to try to import fragment documents which don't exist. What was the intended logic of this line? Looks like maybe the `||` should be `&&`?

Also, this import does not appear to respect [custom prefix/suffix values from ClientSideBaseVisitor](https://github.com/dotansimha/graphql-code-generator/blob/v1.12.2/packages/plugins/other/visitor-plugin-common/src/client-side-base-visitor.ts#L129-L130).

**Comment by dotansimha** [comment]
@mjbcopland can you please share a reproduction for this issue? otherwise we won't be able to tell if we managed to fix that.

**Comment by dotansimha** [comment]
I think this was fixed in the recent PRs. Can you please try `1.12.3-alpha-b89e11fd.107`?

**Comment by zorji** [comment]
@dotansimha I've tested 1.13 and it's still an issue.

The issue is, it generates references to `FragmentDoc` regardless of whether `FragmentDoc` was generated or not.

Having `preset: near-operation-file` can reproduce this issue.

Looks like @mjbcopland pointed out where the issue is because that `if` always evaluate to `true`.

**Comment by dotansimha** [comment]
@zorji I think just using near-operation-file` doesn't reproduce it, it might be something specific to your setup. We have tested `near-operation-file` with different setups and it seems to work, but we probably missed one of the edge cases. 

Can you please create a reproduction for this? with the recent alpha `1.13.1-alpha-84171f94.18`.

**Comment by zorji** [comment]
@dotansimha Hi, I've created a reproduction here https://github.com/zorji/graphql-codegen-3525

Simply run `npx graphql-codegen` and check the generated file `query.types.d.ts`. Thanks.

**Comment by dotansimha** [comment]
Thanks @zorji . 
Your config file seems a bit messy, I first did the following steps:

1. Use the correct configurations. Why do you need to generate operations and resolvers in the same context? is it for client-side state? 

It could simply look like that:

```yml
overwrite: true
generates:
  src/base-types.ts:
    schema: ./src/base.graphql
    plugins:
      - typescript

  src/graphql:
    schema: ./src/base.graphql
    documents:
      - ./src/graphql/**/*.ts
      - '!*.types.d.ts'
    preset: near-operation-file
    presetConfig:
      baseTypesPath: ../base-types.ts
      extension: .types.d.ts
    plugins:
      - typescript-operations

config:
  scalars:
    ID: string
    LocalDate: LocalDate
  maybeValue: T | null | undefined
  skipTypename: true
  preResolveTypes: true
  enumsAsTypes: true
``

2. Your version are not aligned. In codegen versions, we require all versions to be the same. So you `package.json` should look like that (all packages has the same version):

```json
    "@graphql-codegen/cli": "1.13.1-alpha-84171f94.18",
    "@graphql-codegen/near-operation-file-preset": "1.13.1-alpha-84171f94.18",
    "@graphql-codegen/typescript": "1.13.1-alpha-84171f94.18",
    "@graphql-codegen/typescript-operations": "1.13.1-alpha-84171f94.18",
    "@graphql-codegen/typescript-resolvers": "1.13.1-alpha-84171f94.18",
```

3. Regarding the actual bug, I did noticed the import for `..FragmentDoc`. It happens because we expect it to be there, because we assumes people will use `typescript-react-apollo` (or similar, `typescript-apollo-angular`) with the `near-operation-file` preset. This plugins are in charge of generating the `..FragmentDoc` variables.
I tried your repo with `typescript-react-apollo` plugin as well, and it seems to work fine, no more invalid imports.

But when I think about this now, it seems like it's not mandatory. 

I tried to fix most of the issues with the `FragmentDoc` thing, I hope it helps and doesn't create new errors. PR: https://github.com/dotansimha/graphql-code-generator/pull/3644

Alpha version is available: `1.13.1-alpha-a7a3c762.19`.

Can you please try it? @mjbcopland @zorji

**Comment by dotansimha** [comment]
@zorji It seems like `1.13.1-alpha-a7a3c762.19` fixes the issue in your reproduction.

**Comment by pachuka** [comment]
@dotansimha - `1.13.1-alpha-a7a3c762.19` fixes my issue as well!

**Comment by mjbcopland** [comment]
I think I've found the actual root of this issue and a proper fix. Note that the fix in #3644 doesn't actually fix the problem; it only works for the reproduction because it isn't using any of the whitelisted plugins. As an example, I've forked the reproduction [here](https://github.com/mjbcopland/graphql-codegen-3525) and added the typescript-document-nodes plugin.

What I think is causing the issue is the TODO [here](https://github.com/dotansimha/graphql-code-generator/blob/v1.13.0/packages/presets/near-operation-file/src/fragment-resolver.ts#L122). I've had reasonable success adding the `importFrom` property to external fragments, but I've had difficulty getting it running locally due to conflicting versions of graphql etc.

When the `importFrom` property is set, ClientSideBaseVisitor will add an import for the fragment. As each of the plugins use this base visitor, the import will (?) be added as required without the near-operation-file preset making assumptions about whether it is needed.

Changes made on #3646 if anyone wants to give it a go. Sidenote: what's the recommended process for local development? Symlinking the package didn't work well for me.

**Comment by zorji** [comment]
@dotansimha Thanks! Sorry I tried to copy the codegen from one of the existing project and delete the unrelevant stuff so it was a bit messey. And we use Vue instead of React/Angular maybe that's why.

**Comment by dotansimha** [comment]
Fixed in `v1.13.1` 🎉 We'll still improve the implementation in the future, but the current fix should solve the issues.

**Comment by mjbcopland** [comment]
This isn't fixed as shown in the reproduction here https://github.com/mjbcopland/graphql-codegen-3525

I'll accept patching with workarounds until we have a proper fix but I don't understand why issues are being closed.

**Comment by zorji** [comment]
@mjbcopland strange, it fixed the issue for me. However, one thing I noticed is, before this fix, `v1.13.1` has been already released. I think this patch should actually go to `v1.13.2`. Not sure if that causing cache issue on your side.

**Comment by dotansimha** [comment]
@mjbcopland you are mixing too many plugins, that might not be compatible with each other. Can you please use the following, as a base, and let me know if there are other plugins that you might need that are missing and need to be fixed?

```yaml
overwrite: true
schema: ./src/base.graphql
config:
  skipTypename: true
  preResolveTypes: true
  enumsAsTypes: true
  scalars:
    ID: string
    LocalDate: LocalDate
  maybeValue: T | null | undefined
generates:
  src/base-types.ts:
    plugins:
      - typescript

  src/graphql:
    documents:
      - ./src/graphql/**/*.ts
      - "!*.generated.ts"
    preset: near-operation-file
    presetConfig:
      baseTypesPath: ../base-types.ts
      extension: .generated.ts
    plugins:
      - typescript-operations
```
^ This works
