### ISSUE TITLE
Wait for previous generate?

### ISSUE THREAD

**Issue by sarink** [dotansimha/graphql-code-generator#3590]
```
generates:
  ./src/api-schema.json:
    schema: http://localhost:3000/api/graphql
    plugins:
      - introspection

  ./src/api-queries.ts:
    schema: ./src/api-schema.json
    documents: src/queries/*.ts
    plugins:
      - typescript
      - typescript-operations
```
This will fail, because both operations execute simultaneously. Is there any way to wait for the schema.json to download and then use it to generate the queries? I know I could just put the url of the service in the second `schema` too, but I need the schema.json for eslint and I prefer for frontend code to not require the backend services to be running to generate their types

**Comment by dotansimha** [comment]
@kamilkisiela I think it's related to the way we are using `listr`, right?

**Comment by sarink** [comment]
> I know I could just put the url of the service in the second schema too, but I need the schema.json for eslint and I prefer for frontend code to not require the backend services to be running to generate their types

;)

**Comment by dotansimha** [comment]
Currently, there is no way to have dependencies between different file outputs, mainly because each output is independent and we run it in parallel.
 
@kamilkisiela What do you think? you think we can do solve that with `listr`?

**Comment by ardatan** [comment]
@dotansimha We might manage that by changing concurrency limit to 1

**Comment by dotansimha** [comment]
@ardatan yeah this could work, but still we need to manage order or execution somehow

**Comment by ardatan** [comment]
@dotansimha This needs to be tested properly. Since listr takes an array and iterates over jobs to execute them. If there is no execution, it would respect the order of job. But I am not 100% sure

**Comment by ardatan** [comment]
@dotansimha check this https://www.npmjs.com/package/listr#concurrent

**Comment by dotansimha** [comment]
@ardatan yeah but still, if the order of keys under `generates` will be different , it won't work, because we need to understand the dependencies between the outputs.

**Comment by ardatan** [comment]
@dotansimha yes you're right we cannot trust JavaScript objects. Map can be used there to keep the order of keys.

**Comment by dotansimha** [comment]
Also, @ardatan suggested that you'll try to use the programatic API and generate things in order.
At the moment, we do not plan to add a way to create dependencies between outputs.

**Comment by kamilkisiela** [comment]
@dotansimha @ardatan we could collect keys and iterate over `schema` and `documents` to look for it, then with `dependency-graph`, we have a nice solution. When it's a glob, then we check if it matches. It's not expensive but may help a lot.

**Comment by kamilkisiela** [comment]
@dotansimha @ardatan @sarink 
https://github.com/dotansimha/graphql-code-generator/pull/3603

**Comment by dotansimha** [comment]
Fixed in `v1.13.1` 🎉

**Comment by sarink** [comment]
@dotansimha can you explain how this is supposed to work?
```
generates:
  ./src/api-schema.json:
    schema: http://localhost:3000/api/graphql
    plugins:
      - introspection

  ./src/api-queries.ts:
    schema: ./src/api-schema.json
    documents: src/queries/*.ts
    plugins:
      - typescript
      - typescript-operations
```
This is still not working for me. I also tried making each of the keys an array (ie, `- ./src/api-queries.ts`), but that had no effect either. I'm confused

**Comment by sarink** [comment]
Bump?

**Comment by kamilkisiela** [comment]
@sarink we reverted it because generation happens before CLI persists the output to file system, so it awaits forever or completes before we save anything to disk. I could work on it but not in next week or two.

**Comment by sarink** [comment]
Ah, I see, that explains it. Thanks :)

**Comment by ardatan** [comment]
@sarink In the meanwhile, I recommend you to use programmatic API to generate each file by synchronously waiting each other
