### ISSUE TITLE
v1.15.0 generating duplicate fragment definitions

### ISSUE THREAD

**Issue by ggascoigne** [dotansimha/graphql-code-generator#4143]
**Describe the bug**

I have a graphql directory containing a number of .graphql files containing a mix of queries, mutation and fragments.  I'm using the #import syntax to reference fragments across files so that they compile correctly.

This has worked very nicely up to and including v1.14.0.

Upgrading to v1.15.0 causes the resulting typescript file to contain multiple definitions of some of the fragment types.  Note that the codegen works without problem, it just doesn't generate an output that can compile.

You can see this in:

https://codesandbox.io/s/elegant-forest-vlzlz?file=/types.ts

Search for GameGmsFragment in types.ts, you'll see that there are two of them.

I could add more details but to be honest, the codesandbox example reproduces the problem in far more detail than I could easily describe here.

**Comment by dotansimha** [comment]
duplicate https://github.com/dotansimha/graphql-code-generator/issues/3990

**Comment by dotansimha** [comment]
Fixed in : https://github.com/dotansimha/graphql-code-generator/pull/4148

**Comment by wuichen** [comment]
i have done npx match-version @graphql-codegen 1.15.1-alpha-12a4da72.33+12a4da72 to upgrade to this fix but im still seeing the problem. this is my codegen file `overwrite: true
schema: 'src/generated/schema.graphql'
documents: 'src/graphql/auto/**/*.graphql'
generates:
  src/generated/index.ts:
    plugins:
      - 'typescript'
      - 'typescript-operations'
      - 'typescript-react-apollo'
      - 'typescript-graphql-request'
    config:
      withHooks: true
      withComponent: false
      withHOC: false
      withMutationFn: false
      maybeValue: T | null
      reactApolloVersion: 3
`

**Comment by dotansimha** [comment]
@wuichen can you please share a reproduction of the issue? it's seems like a different thing. 

Also, why do you need `typescript-react-apollo` and `typescript-graphql-request` together in the same file? what's your use case?

In most cases, if you are developing a frontend, use `typescript-react-apollo`, if it's a backend, use `typescript-graphql-request`. Those are 2 different plugins for 2 different GraphQL client libraries.

**Comment by lassesteffen** [comment]
I have the same problem and I just use 

```
generates:
  src/graphql/generatedTypes.ts:
    plugins:
      - 'typescript'
      - 'typescript-operations'
    config:
      preResolveTypes: true

```

**Comment by dotansimha** [comment]
@lassesteffen can you please share a reproduction? It's not coming from your list of plugins, it's probably a version or a document that causes that.

**Comment by dhalbrook** [comment]
Seeing the same.  My config:

```javascript
{
  "overwrite": true,
  "schema": [
    "./graphql/**/*.graphqls",
    "../dev/lia/apps/main/res/lia/res/graphql/*.graphqls"
  ],
  "documents": ["graphql/**/*.graphql", "components/**/*.graphql"],
  "generates": {
    "types/graphql-fragment-types.ts": {
      "plugins": ["fragment-matcher"]
    },
    "types/graphql-types.tsx": {
      "plugins": ["typescript", "typescript-operations", "typescript-react-apollo"]
    }
  }
}
```

**Comment by dotansimha** [comment]
@dhalbrook can you please share a reproduction? It's not coming from your list of plugins, it's probably a version or a document that causes that.

**Comment by dmarkow** [comment]
Still happening here on 1.15.1.

- 1.15.1:  https://codesandbox.io/s/autumn-hooks-2627b?file=/documents/user.d.ts
- 1.14.0:  https://codesandbox.io/s/cranky-mendel-6sm1e?file=/documents/user.d.ts

Note that in 1.15.1, the `user.d.ts` and `users.d.ts` files are redefining and re-exporting `UserFieldsFragment`, whereas in 1.14.0 they import the fragment from the `fragment.d.ts` file.

Config:

```yaml
schema: schema.graphql
documents: documents/**/*.graphql
generates:
  types.ts:
    plugins:
      - typescript
  documents/:
    preset: near-operation-file
    presetConfig:
      extension: .d.ts
      baseTypesPath: types.ts
    plugins:
      - typescript-operations
config:
  skipGraphQLImport: true
```

**Comment by dmarkow** [comment]
@ardatan That was actually left over from another sandbox I used for this. I just removed the skipGraphQLImport line and the issue is still happening. In my main app I'm not using skipGraphQLImport and still started having these same issues as of 1.15.0.

https://codesandbox.io/s/inspiring-http-tmu8g?file=/documents/user.d.ts

**Comment by ardatan** [comment]
As you can see in the sandbox I sent, I am using canary version which hasn't released yet and `skipGraphQLImport` works as expected. It ignores `#import` so every single file is processed only with its own content without imported stuff. 
If you don't use `skipGraphQLImport`, it is expected to have that fragment typings together with other typings because it is imported by that file independently. It is not duplicated.

**Comment by wuichen** [comment]
@dotansimha the error I was seeing is duplicated fragment docs from the generated files. I had two of the library inside cuz I was experimenting using apollo queries and also wrapping graphql calls in rest endpoints.

**Comment by ggascoigne** [comment]
I can confirm that upgrading to v1.15.1 fixes my problem - thank you for digging into this so promptly.

**Comment by dotansimha** [comment]
Fixed in `v1.15.2`

**Comment by jwjuele** [comment]
Hey everyone,
i'm currently using `@graphql-codegen/cli v1.21.3` and it seems like i'm still facing the issue of having duplicate fragments in my generated typescript documents and their final queries.

```
    "@graphql-codegen/cli": "1.21.3",
    "@graphql-codegen/fragment-matcher": "2.0.1",
    "@graphql-codegen/introspection": "^1.18.1",
    "@graphql-codegen/near-operation-file-preset": "^1.17.13",
    "@graphql-codegen/schema-ast": "^1.18.1",
    "@graphql-codegen/typescript": "^1.21.1",
    "@graphql-codegen/typescript-apollo-angular": "2.3.2",
    "@graphql-codegen/typescript-graphql-files-modules": "1.18.1",
    "@graphql-codegen/typescript-operations": "^1.17.15",
```

I have to admit that i have a huge project where i make an extensive use of fragments, which themselves contain fragments and so on...

When i view my `*.generated.ts` files it seems quite logically, that typescript imports include other `*.generated.ts` files in which fragments are used repeatedly and therefore imported again.

Is this behaviour related to this issue and should it be solved by now?

Btw - my `codegen.yml`:

```
generates:
    apps/public:
        schema:
            - ./libs/ep-shared/src/lib/core/graphql/schema.graphql
        documents:
            - ./libs/shared/**/*.graphql
        preset: near-operation-file
        presetConfig:
            extension: .generated.ts
            typesPath: "@ep-shared/core/graphql/"
            schemaTypesPath: ./libs/shared/src/lib/ep-core/graphql/graphql-types.ts
            baseTypesPath: ./../../libs/shared/src/lib/ep-core/graphql/graphql-types.ts
        config:
            withHOC: false
            withHooks: true
            noNamespaces: false
            schemaDescription: false
            declarationKind:
                union: type
                type: interface
                scalar: interface
                input: interface
                arguments: interface
                interface: interface
            descriptions: false
            commentDescriptions: true
            excludes: ./node_modules/**
            hooksImportFrom: angular-apollo
        plugins:
            - typescript-operations
            - typescript-apollo-angular
```

**Comment by ardatan** [comment]
Could you create a seperate issue with a reproduction CodeSandbox? And also a failing test would be so much helpful to help us to fix the issue quicker?

**Comment by jwjuele** [comment]
Oh, guess the bug was sitting in front of the screen this time. Thanks for you quick reply though.
Loggin the generated Document in console showed an object containing a property source, which included those duplicate fragments, but the fired query in my network seems to be fine and cleaned off the duplicates. Thanks anyway!

**Comment by matthieudesprez** [comment]
In my case it was caused by having a mutation named CreateUser on the client side while being named create_user on the server side, it resulted in duplicated generated types for CreateUser
