### ISSUE TITLE
v2 apollo-react plugin enforces tsx by default

### ISSUE THREAD

**Issue by SimenB** [dotansimha/graphql-code-generator#4499]
**Describe the bug**

https://github.com/dotansimha/graphql-code-generator/releases/tag/%40graphql-codegen%2Ftypescript-react-apollo%402.0.0 says `withComponent: false` is the default behavior, but that forces the generated file to be `tsx` instead of `ts`.

https://github.com/dotansimha/graphql-code-generator/blob/8f31a9a9d74f556975e5bdb3c92dc8da8a578be6/packages/plugins/typescript/react-apollo/src/index.ts#L36-L51

Adding an explicit `withComponent: false` fixes the issue

**To Reproduce**

1. My GraphQL schema:

N/A

2. My GraphQL operations:

N/A

3. My `codegen.yml` config file:

```yml
config:
  reactApolloVersion: 2
generates:
  src/:
    schema:
      - schema.graphql
    documents: src/**/*.graphql
    preset: near-operation-file
    presetConfig:
      baseTypesPath: gqltypes.ts
    plugins:
      - typescript-operations
      - typescript-react-apollo
```

**Expected behavior**

**Environment:**

- OS: macOS
- `@graphql-codegen/...`: 1.17.7 plus v2 of react apollo 
- NodeJS: 12.18.1

**Additional context**

**Comment by dotansimha** [comment]
Thanks @SimenB ! I guess we need to validate extensions based on configuration provided. I will look into it :)

**Comment by SimenB** [comment]
Flipping to only enforcing `tsx` if `withComponent: true` should fix it, I believe 🙂

**Comment by dotansimha** [comment]
@SimenB can you please try `@graphql-codegen/typescript-react-apollo@2.0.2-alpha-e78a37d8.0`?

**Comment by SimenB** [comment]
Yeah, that alpha works great!

**Comment by dotansimha** [comment]
Fixed in `@graphql-codegen/typescript-react-apollo@2.0.4`

**Comment by yudiz-bhoomit** [comment]
Nope issue is still there 

`
import { CodegenConfig } from '@graphql-codegen/cli';

const config: CodegenConfig = {
    schema: 'https://countries.trevorblades.com/graphql',
    documents: ['./src/**/*.gql', './src/**/*.graphql'],
    ignoreNoDocuments: true,
    generates: {
        './src/graphql/generated/': {
            plugins: [
                {
                    typescript: {},
                },
                {
                    'typescript-operations': {},
                },
                {
                    'typescript-react-apollo': {},
                },
            ],
        },
    },
    config: {
        withHooks: true,
        withComponent: false,
    }
};

export default config;
`

This is my config other problem is also that it is generating types twice
