### ISSUE TITLE
Better support for loading plugins when using Yarn v2

### ISSUE THREAD

**Issue by mrtnbroder** [dotansimha/graphql-code-generator#4766]
**Describe the bug**
 

When trying to use external plugins like `graphql-codegen-apollo-next-ssr` with yarn v2, the cli is trying to look for ` @graphql-codegen/graphql-codegen-apollo-next-ssr` which causes an error with yarn v2.

```
 Unable to load template plugin matching 'graphql-codegen-apollo-next-ssr'.
                  Reason:
                    @graphql-codegen/cli tried to access @graphql-codegen/graphql-codegen-apollo-next-ssr, but
 it isn't declared in its dependencies; this makes the require call ambiguous and unsound.

    Required package: @graphql-codegen/graphql-codegen-apollo-next-ssr (via "@graphql-codegen/graphql-codegen-
apollo-next-ssr")
    Required by: @graphql-codegen/cli@virtual:2e4a546c98da4032db6b07cf4e91653b3f8547d84f83ed1956838abce54d5b79
47b8134ef943904cc7e53db132963a47bc02791f768239a1502cedcc9d502dd1#npm:1.17.8 (via
/usr/local/app/.yarn/$$virtual/@graphql-codegen-cli-virtual-16408af03c/0/cache/@graphql-codegen-cli-npm-1.17.8
-a51601b2d4-5d03c4b055.zip/node_modules/@graphql-codegen/cli/)
```

**To Reproduce**

upgrade to yarn v2, use third-party plugin that is not starting with `@graphql-codegen/*` and get the error.

One way to fix this issue would be to not try to prefix plugin names with `@graphql-codegen/` and take the name of the plugin in the `codegen.yml` as-is.

From:
```yml
graphql/schema.ts:
    plugins:
      - typescript
      - typescript-operations
```

To:
```yml
graphql/schema.ts:
    plugins:
      - @graphql-codegen/typescript
      - @graphql-codegen/typescript-operations
```

**Comment by dotansimha** [comment]
@mrtnbroder can you please try latest version of the cli/core? we fixed the issues related to Yarn v2 compatibility. (also, please refer to my comment on your PR. Thanks!)

**Comment by mrtnbroder** [comment]
Hi @dotansimha 
Thanks, I just tried it out. I am on `1.17.9` for `@graphql-codegen/cli`, but I am still getting the same error for third-party plugins.

```
  ✔ Parse configuration
  ❯ Generate outputs
    ❯ Generate to src/graphql/page.tsx (using EXPERIMENTAL preset "import-types-preset")
      ✔ Load GraphQL schemas
      ✔ Load GraphQL documents
      ✖ Generate
        → Unable to load template plugin matching graphql-codegen-apollo-next-ssr
    ✔ Generate src/graphql/schema.ts


 Found 1 error

  ✖ src/graphql/page.tsx
    Unable to load template plugin matching 'graphql-codegen-apollo-next-ssr'.
                  Reason:
                    Your application tried to access @graphql-codegen/graphql-codegen-apollo-next-ssr, but it i
sn't declared in your dependencies; this makes the require call ambiguous and unsound.

    Required package: @graphql-codegen/graphql-codegen-apollo-next-ssr (via "@graphql-codegen/graphql-codegen-a
pollo-next-ssr")
    Required by: /usr/local/app/

    Require stack:
    - /usr/local/app/__fake.js
    Error: Unable to load template plugin matching graphql-codegen-apollo-next-ssr
        at getPluginByName (/usr/local/app/.yarn/$$virtual/@graphql-codegen-cli-virtual-ad28152322/0/cache/@gra
phql-codegen-cli-npm-1.17.9-a29b4358cd-a04504bbab.zip/node_modules/@graphql-codegen/cli/bin.js:285:23)
        at async Promise.all (index 0)
        at async /usr/local/app/.yarn/$$virtual/@graphql-codegen-cli-virtual-ad28152322/0/cache/@graphql-codege
n-cli-npm-1.17.9-a29b4358cd-a04504bbab.zip/node_modules/@graphql-codegen/cli/bin.js:828:60
    Error: Unable to load template plugin matching graphql-codegen-apollo-next-ssr
        at getPluginByName (/usr/local/app/.yarn/$$virtual/@graphql-codegen-cli-virtual-ad28152322/0/cache/@gra
phql-codegen-cli-npm-1.17.9-a29b4358cd-a04504bbab.zip/node_modules/@graphql-codegen/cli/bin.js:285:23)
        at async Promise.all (index 0)
        at async /usr/local/app/.yarn/$$virtual/@graphql-codegen-cli-virtual-ad28152322/0/cache/@graphql-codege
n-cli-npm-1.17.9-a29b4358cd-a04504bbab.zip/node_modules/@graphql-codegen/cli/bin.js:828:60
```

**Comment by dotansimha** [comment]
Keeping open. Not really sure what should be needed to support that, I guess some checks for Yarn v2. PRs are welcome :)

**Comment by mrtnbroder** [comment]
I am also unsure how to fix. I am asking the yarn team now for help. https://github.com/yarnpkg/berry/issues/1895

**Comment by dotansimha** [comment]
Fixed in `@graphql-codegen/cli@1.17.10`.

**Comment by richiejd** [comment]
As a follow up on this, I am having this issue still in v1.20.1
"Your application tried to access @graphql-codege/@my-scope/my-package"

The above only happens on windows (mac, linux are fine as it is indeed installed), the issue seems to be something else.

Looked at the fix
https://github.com/dotansimha/graphql-code-generator/commit/2900ee291ae1acef2853629a46da5efcf8c465d5#diff-90ada7a3e08309896ec869a530fe35cb231e605934a04290d9bfcf711edc9bbb
and the file (as of the fix)
https://github.com/dotansimha/graphql-code-generator/blob/2900ee291ae1acef2853629a46da5efcf8c465d5/packages/graphql-codegen-cli/src/plugins.ts

and I'm still getting "Unable to load template plugin..." so I need to look into why the error thrown is not `MODULE_NOT_FOUND` specifically on windows
will report back once I have more info/resolve. posting more for a trace for others. no action from @graphql-codegen folks

**Comment by richiejd** [comment]
@dotansimha the current check here:
https://github.com/dotansimha/graphql-code-generator/blob/master/packages/graphql-codegen-cli/src/plugins.ts#L25

Is not OS-safe.
This is because when we require a package that has an additional @scope then we end up with the following situation:

graphql-codegen first tries to require
`@graphql-codegen/@scope/package`

the error that arises from this is the following
```
Your application tried to access @graphql-codegen/@scope, but it isn't declared in your dependencies; this makes the require call ambiguous and unsound.

Required package: @graphql-codegen/@scope (via "@graphql-codegen/@scope/package")
Required by: /...

Require stack:
- /...
```

On linux and mac, the separator matches with the package naming convention so it works, but on windows you get
`Required package: @graphql-codegen/@scope (via "@graphql-codegen\@scope\package")`

thus the name is not found as it's not an exact match

**Comment by dotansimha** [comment]
> ``
> 
> Is not OS-safe.
> This is because when we require a package that has an additional @scope then we end up with the following situation:
> 
> graphql-codegen first tries to require
> `@graphql-codegen/@scope/package`
> 
> the error that arises from this is the following
> 
> ```
> Your application tried to access @graphql-codegen/@scope, but it isn't declared in your dependencies; this makes the require call ambiguous and unsound.
> 
> Required package: @graphql-codegen/@scope (via "@graphql-codegen/@scope/package")
> Required by: /...
> 
> Require stack:
> - /...
> ```

Seems like a different issue here. Can you please report a new issue with a reproduction?
