### ISSUE TITLE
Bug: interfacePrefix Not working Properly

### ISSUE THREAD

**Issue by daniel-nagy** [dotansimha/graphql-code-generator#483]
This option is prefixing enums and types when used on other types or interfaces.

e.g. it produces the following:

```typescript
export enum Foo = {
  ...
}

export type Bar = {
  ...
}

export interface IBaz {
  foo: IFoo; // Cannot find name 'IFoo'.
  bar: IBar; // Cannot find name 'IBar'.
}
```

**graphql-code-generator**: v0.10.7
**graphql-codegen-typescript-template**: v0.10.7

**Comment by kamilkisiela** [comment]
@daniel-nagy Hi, could you create a simple reproduction or a failing test?

**Comment by daniel-nagy** [comment]
@kamilkisiela modify this test https://github.com/dotansimha/graphql-code-generator/blob/master/packages/templates/typescript/tests/typescript.spec.ts#L54

with

```diff
it('should handle interfacePrefix option correctly', async () => {
    const { context } = compileAndBuildContext(`
+     enum Test {
+       PROP
+     }
      type Foo {
        bar: Bar
+       test: Test
      }
      type Bar {
        qux: String
      }
    `);
    const compiled = await compileTemplate(
      {
        ...config,
        config: {
          interfacePrefix: 'I'
        }
      } as GeneratorConfig,
      context
    );

    const content = compiled[0].content;

    console.log('CONTENT', content);

    expect(content).toBeSimilarStringTo(`
      interface IFoo {
        bar?: IBar | null;
+       test?: Test | null;
      }
    `);
  });
```

It will fail, the code being generated is 

```typescript
export interface IFoo {
  bar?: IBar | null; 
  test?: ITest | null; 
}
      
export interface IBar {
  qux?: string | null; 
}
      
export enum Test {
  PROP = "PROP",
}
```

You can see the enum is being prefixed with `I` when used on the type `Foo`.

As for my original comment, type `Bar` is part of a client side query document. So something like

```typescript
const getBarQuery = gql`
  query GetBar($id: ID!) {
    bar(id: $id) {
      id
    }
  }
`;
```

Will produce

```typescript
export namespace GetBar {
  export type Variables = {
    id: string;
  };

  export type Query = {
    __typename?: "Query";
    bar: IBar | null; // Cannot find name 'IBar'.
  };

  export type Bar = {
    __typename?: "Bar";
    id: string;
  };
}
```

**Comment by dotansimha** [comment]
Done! 0.11 is available now. @daniel-nagy

**Comment by daniel-nagy** [comment]
@dotansimha Thanks for the update. Unfortunately, client query documents are still not working. I'm getting the exact same behavior as before. It generates types without the prefix but when it uses the type it adds the prefix.

I also think it is undesirable to add the interface prefix to an enum type, which is what is happening now.

**Comment by cerino-ligutom** [comment]
@daniel-nagy Was trying to find a workaround on the issue about interfacePrefix value being added on enums automatically (e.g. just importing the enum directly through add plugin and emptying the enum value on the enums config) but I think it got fixed on v1.16.0 as the imported enum is being aliased now.
