### ISSUE TITLE
[typescript] Why is parent/args hardcoded as optional?

### ISSUE THREAD

**Issue by jzimmek** [dotansimha/graphql-code-generator#489]
Hi there, awesome project to make server-side graphql even more enjoyable.

I just generated some typescript typings

```
gql-gen --schema ./schema.js --template graphql-codegen-typescript-template --out ./typings/
```

It generated typings/types.ts as expected:

```
...
export type Resolver<Result, Parent = any, Context = any, Args = any> = (
  parent?: Parent,
  args?: Args,
  context?: Context,
  info?: GraphQLResolveInfo
) => Promise<Result> | Result;
...
```

"parent" and "args" are optional, this is hardcoded in:

https://github.com/dotansimha/graphql-code-generator/blob/master/packages/templates/typescript/src/schema.handlebars#L5-L7

AFAIK the "parent" field is only optional for root types Query/Mutation/Subscription.

The "args" field should only be optional if the corresponding graphql field arguments are optional.

Am I doing something wrong?

**Comment by dotansimha** [comment]
@kamilkisiela @ardatan

**Comment by kamilkisiela** [comment]
I would make them non optional, because in most cases they are. 
This will hurt a bit while unit testing:

```ts
fooResolver({} as any, {}, context, {} as any)
```

But.

You can always wrap resolvers with this function in unit tests:

```ts
type MockResolver<Result, Args> = (
  parent?: any,
  args?: Args,
  context?: any,
  info?: any
) => Promise<Result> | Result;

export function mockResolver<R, A>(
  resolver: Resolver<R, A>
): MockResolver<R, A> {
  return (parent, args, context, info) => resolver(parent, args, context, info);
}
```

This will make all arguments optional and TS, that weird mad beast, won't scream

**Comment by kamilkisiela** [comment]
@dotansimha @ardatan @jzimmek

**Comment by dotansimha** [comment]
@kamilkisiela I agree with your approach.

**Comment by dotansimha** [comment]
Done! 0.11 is available now. @jzimmek

**Comment by stomvi** [comment]
I am still getting optional `parent`, `args` and `context` using `graphql-codegen-flow-resolvers`.

"graphql-codegen-flow": "^0.18.0",
"graphql-codegen-flow-resolvers": "^0.18.0",

**Comment by dotansimha** [comment]
@stomvi why shouldn't they be optional? You don't have to declare all of them in each resolver.

**Comment by loicplaire** [comment]
@dotansimha it should match [the TS declaration](https://github.com/dotansimha/graphql-code-generator/blob/master/packages/plugins/typescript-resolvers/src/index.ts#L114).

Furthermore, if you look at [the `graphql-js` typedefs](https://github.com/graphql/graphql-js/blob/c82ff68f52722c20f10da69c9e50a030a1f218ae/src/type/definition.js#L482), you'll see that they are not optional. They are always provided, but it doesn't mean that you have to use them in each resolvers.

I am happy to create a PR with the changes.

**Comment by dotansimha** [comment]
@loicplaire Regarding the TypeScript plugin, was already fixed. Which version do you use? 
See here: https://github.com/dotansimha/graphql-code-generator/blob/master/packages/plugins/typescript-resolvers/src/index.ts#L114-L119

**Comment by loicplaire** [comment]
> @loicplaire Regarding the TypeScript plugin, was already fixed. Which version do you use?
See here: https://github.com/dotansimha/graphql-code-generator/blob/master/packages/plugins/typescript-resolvers/src/index.ts#L114-L119

My point was that the Flow declarations should match the TS ones. [The changes that were made to the TS ones](https://github.com/dotansimha/graphql-code-generator/pull/509/files) (removing optionality) should be applied to the Flow ones as well. 

E.g.:

```js
// Flow declaration
export type Resolver<Result, Parent = {}, Context = {}, Args = {}> = (
  parent: Parent,
  args: Args,
  context: Context,
  info: GraphQLResolveInfo
) => Promise<Result> | Result;
```

**Comment by dotansimha** [comment]
@loicplaire you are right, I opened an issue for it: https://github.com/dotansimha/graphql-code-generator/issues/1725
