### ISSUE TITLE
enum type error when snake case

### ISSUE THREAD

**Issue by shinyaohira** [dotansimha/graphql-code-generator#497]
I'm using v0.10.7 and having a issue with the casing in generated typescript types not matching.

schema:
```
enum color_name {
  blue
  red
  white
}

type Query {
  hello: color_name
}
```

generated types:
```
export interface Query {
  hello?: ColorName | null;    ### <- pascal case
}

export enum color_name {    ### <- snake case
  yello = "yello",
  black = "black",
  red = "red"
}

export namespace QueryResolvers {
  export interface Resolvers<Context = any> {
    hello?: HelloResolver<ColorName | null, any, Context>;    ### <- pascal case
  }

  export type HelloResolver<
    R = ColorName | null,    #### <- pascal case
    Parent = any,
    Context = any
  > = Resolver<R, Parent, Context>;
}
```

**Comment by dotansimha** [comment]
@kamilkisiela

**Comment by Slessi** [comment]
Would it be possible to not modify scalar names?

I don't see why the outputted types should be to the way they are specified in schema

(mentioned also in https://github.com/dotansimha/graphql-code-generator/issues/153#issuecomment-411335625)

**Comment by dotansimha** [comment]
Done! 0.11 is available now. @shinyaohira

**Comment by shinyaohira** [comment]
I upgraded the version to 0.16.0, and the problem still occurs. It might be related to #1193 and fixed soon?

**Comment by shinyaohira** [comment]
@dotansimha it worked! thank you.

btw, I found another problem. when I define a lowercase custom scalar type, and use `keep` namingConvention, gql-gen generates a lowercase custom type and a pascal case type as the reference.

**Comment by shinyaohira** [comment]
@dotansimha I opened the issue #1297 . thank you.
