### ISSUE TITLE
[typescript-resolvers] Unable to call resolvers in tests in version 1.20.0

### ISSUE THREAD

**Issue by mvanalphen** [dotansimha/graphql-code-generator#6310]
**Describe the bug**
Prior to version 1.20.0, we were able to import and call resolvers in our tests to verify their behaviour. However, as of version 1.20.0 of `typescript-resolvers`, we are no longer able to call the resolvers. 

I believe this may be a result of https://github.com/dotansimha/graphql-code-generator/pull/6281, which allows for resolvers to either be of type `ResolverFn` or `ResolverWithResolve`.

The following error is thrown:
```
This expression is not callable.
  Not all constituents of type 'Resolver<Maybe<ResolverTypeWrapper<Example>>, {}, Context, RequireFields<QueryExampleArgs, "input">>' are callable.
    Type 'ResolverWithResolve<Maybe<ResolverTypeWrapper<Example>>, {}, Context, RequireFields<QueryExampleArgs, "input">>' has no call signatures.
```

**To Reproduce**

My `codegen.yml` config file:

```yml
overwrite: true
schema: src/graphql/**/*.gql
documents: null
generates:
  src/generated/graphql.ts:
    plugins:
      - 'typescript'
      - 'typescript-resolvers'
    config:
      contextType: ../config#Context
      federation: true
      namingConvention:
        enumValues: keep
      noSchemaStitching: true
      optionalInfoArgument: true
      useIndexSignature: true

hooks:
  afterAllFileWrite:
    - yarn prettier -w
    - yarn eslint --fix || true
```

**Expected behavior**
Ideally, we should be able to call our tests as we did in the past. Or is there some way to indicate that the resolvers are always of type `ResolverFn`?

**Environment:**

- OS: Windows 10
- `@graphql-codegen/typescript-resolvers`: 1.20.0 
- NodeJS: 14.15.0

**Comment by dotansimha** [comment]
@highwide @ardatan I think it's related to https://github.com/dotansimha/graphql-code-generator/pull/6281 ?

**Comment by highwide** [comment]
> I think it's related to #6281 ?

I guess so too.
But I won't find how to fix quickly, I apologize.

**Comment by Cretezy** [comment]
Would be great to have an optional to disable this, as it's also blocking me. Maybe an option called `disabledResolverFnSubtype`?

**Comment by puchm** [comment]
I found a work around for this. Previously I did something like this when declaring resolvers because resolvers can be undefined:

```ts
export const someResolver: Exclude<MutationResolvers['someResolver'], undefined> = async (parent, args, context, info) => {
     /* Resolver definition */
}
```
This made sure that whenever I import the resolver in another file it is callable **prior to 1.20.0**.

With the new changes it can be adjusted to this:
```ts
export const someResolver: Extract<MutationResolvers['someResolver'], Function> = async (parent, args, context, info) => {
    /* Resolver definition */
}
```
This will make sure that the resolver is always callable because it cuts the type down to only the things that are functions.

Hope this helps.

**Comment by joual** [comment]
I'm running into the same issue. Unfortunately @puchm's solution won't work for me because most of our resolvers are defined inline and our root object just gets assigned `Resolvers`. 

We used to just do

```
import resolvers from '../mutations';

// In test files we can assume the resolvers exist
const deleteUser = resolvers.Mutation!.deleteUser!;
```

but now that doesn't work :(

**Comment by chenrui333** [comment]
I am running into this same issue when upgrading resolvers from `1.15.0` to `2.1.1`

**Comment by ardatan** [comment]
First of all, it is not a bug. It is a kind of fix/feature actually because this is the valid signature GraphQL Tools supports. We'd love to accept any PRs for a configuration field that removes `ResolverWithResolve` from the `Resolver` union.

**Comment by dotansimha** [comment]
Thanks @diggs1711 for fixing it in a PR. 
I released a version with a fix for this: `@graphql-codegen/typescript-resolvers@2.3.0`.

You can now add: `makeResolverTypeCallable: true` to your config to apply this.

**Comment by garrett-gottlieb** [comment]
I'm still getting the same error. Maybe I'm defining the type for the resolver incorrectly?

```ts
export const createSubscription: MutationResolvers['createSubscription'] =
  async (_parent, { input: { iosTransactionReceipt } }, context) => {
```

Usage:
```ts
await createSubscription(root, args, context, info)
```

Result:
```
(alias) const createSubscription: Resolver<ResolverTypeWrapper<{}>, {}, any, RequireFields<MutationCreateSubscriptionArgs, "input">> | undefined
import createSubscription
Cannot invoke an object which is possibly 'undefined'.ts(2722)
```
