### ISSUE TITLE
Duplicate identifier error

### ISSUE THREAD

**Issue by shinyaohira** [dotansimha/graphql-code-generator#642]
**Describe the bug**
Duplicate resolver type is generated.

**To Reproduce**
1. Define field `category_sports: category` as schema. (single underscore)
2. Define another field `category__sports: [category]` as schema. (double underscore)
3. Run the following command: `gql-gen -s http://somewhere/graphql -t graphql-codegen-typescript-template -o ./src/resolvers/types.ts ./src/resolvers/query.ts`
4. Run the following command: `tsc -p .`
    src/resolvers/types.ts - error TS2300: Duplicate identifier 'CategorySportsResolver'.

**Expected behavior**
No error message.

**Environment:**
 - OS: macOS High Sierra
 - Codegen: graphql-code-generator v0.12.5, graphql-codegen-typescript-template@0.12.5
 - Node: v8.12.0

**Comment by geotry** [comment]
It happens also for me when my schema contains both `_id` and `id` fields. It generates twice the type `IdResolver`

**Comment by dotansimha** [comment]
It's related to the fact that our `pascalCase` handler does not bahave nicely with underscores. It removes them. We did a fix for it for fields that starts with `_`, but I guess that's not enough.

I'll take a look soon.

Thanks @shinyaohira for reporting it!

**Comment by dotansimha** [comment]
Fixed in >0.14

**Comment by brandondoran** [comment]
It seems the duplicate resolver type is happening in in 0.15.2.  I just upgraded from 0.13. I had resolvers turned off there but decided to give it a try after the upgrade but ran into Typescript build errors due to the duplicates. I have some types in my schema with legacy fields that are in snake_case (such as `brand_id`) but have new fields in camelCase (`brandId`).

I think I could use a custom `namingConvention` to workaround but would be great If it was handled by the package.

Btw, I love this project!  Great work and thanks!

**Comment by dotansimha** [comment]
@brandondoran we fixed this issue in the recent refactor, it will be available very soon in 1.0.0.

**Comment by danbruegge** [comment]
Hi, looks like this error is back again? We have a simple GatsbyJS+StrapiJS stack.

This is what i get:
```$ tsc --noEmit
src/graphqlTypes.ts:868:3 - error TS2300: Duplicate identifier 'PluginCreatorId'.

868   PluginCreatorId = "pluginCreator___id",
      ~~~~~~~~~~~~~~~

src/graphqlTypes.ts:932:3 - error TS2300: Duplicate identifier 'PluginCreatorId'.

932   PluginCreatorId = "pluginCreatorId",```

Do you need further infos?

**Comment by dotansimha** [comment]
@danbruegge can you please open a new issue for that with all the info? It seems like it's a different issue.

**Comment by panzerdp** [comment]
@danbruegge,
Faced the same problem. 

It happens because `"pluginCreator___id"` and `"pluginCreatorId"` using `change-case#pascalCase` is transformed into the same `PluginCreatorId`.

Changing the enum transformer name convention to `keep` solved the problem:

```yaml
# codegen.yaml
config:
  namingConvention:
    enumValues: keep
```

**Comment by danbruegge** [comment]
@panzerdp nice, it works great. Thank you. :)

**Comment by RIP21** [comment]
If there is `pluginCreatorId` and `pluginCreator_____Id`
It generates one and only `PluginCreatorId` causing duplicate. Reproducible with gatsby-netlify-template schema.
With defaults e.g. PascalCase casing setup for enum.

So reopen and try to fix it somehow. Could cause a lot of headaches for some. For me is fine to change casing to `keep`, because I only start a project, but for some, it can be a no go problem.

**Comment by Sawtaytoes** [comment]
> @dotansimha @danbruegge, Faced the same problem.
> 
> It happens because `"pluginCreator___id"` and `"pluginCreatorId"` using `change-case#pascalCase` is transformed into the same `PluginCreatorId`.
> 
> Changing the enum transformer name convention to `keep` solved the problem:
> 
> ```yaml
> # codegen.yaml
> config:
>   namingConvention:
>     enumValues: keep
> ```

This doesn't fix it for me.

Here's my config:
```ts
import { CodegenConfig } from '@graphql-codegen/cli'

const codegenConfig: (
  CodegenConfig
) = {
  config: {
    arrayInputCoercion: false,
    avoidOptionals: true,
    namingConvention: {
      enumValues: "keep", // This is not working.
    },
    skipTypename: true,
    skipTypeNameForRoot: true,
    useTypeImports: true,
  },
  generates: {
    // ...
  },
  emitLegacyCommonJSImports: false,
  ignoreNoDocuments: true,
  overwrite: true,
}
```

**Comment by Sawtaytoes** [comment]
After some more work looking around, I think something is very wrong here.  There's a part in the `graphql.ts` file called `Scalars`:
```
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
```
Even this is duplicated in my output. Might be a separate bug.

To add to the previous post, you can also pass `namingConvention: "keep"`.

**Comment by tylerjbainbridge** [comment]
I'm having the same issue @Sawtaytoes, do you remember what fixed it?

**Comment by alyonium** [comment]
I have the same problem as @tylerjbainbridge & @Sawtaytoes
