### ISSUE TITLE
request to url failed, reason: connect ECONNR EFUSED 127.0.0.1:8001

### ISSUE THREAD

**Issue by Lucasmiguelmac** [dotansimha/graphql-code-generator#7479]
**Describe the bug**
 

**To Reproduce**
1. Start a blank Svelte project
2. Install required dependencies:
```
npm install @graphql-codegen/cli -D

npm i @graphql-codegen/typescript @graphql-code
gen/typescript-operations -D

npm i @graphql-codegen/typescript-urql @graphql
-codegen/urql-introspection @graphql-codegen/urql-svelte-operations-stor
e -D

npm i @urql/svelte urql graphql
```
3. Create a `codegen.yml` config:
```yml
overwrite: true
schema: "http://localhost:8001/"
documents: "src/**/*.graphql"
config:
  withHooks: false
generates:
  src/graphql/generated/graphql.ts:
    plugins:
      - "typescript"
      - "typescript-operations"
      - "typescript-urql"
      - "urql-svelte-operations-store"
```
4. Create a script in `package.json` for codegen:
```json
{
...
"scripts": {
  ...
  "generate": "graphql-codegen --config codegen.yml"
  ...
}
...
}
```

5. Have a backend API running on localhost:8001
![image](https://user-images.githubusercontent.com/49038881/152701392-c3710721-fb0c-4be6-a454-6905dbe224a3.png)

6. Run `npm run generate`

7. Get the error:
```
> generate
> graphql-codegen --config codegen.yml

  ✔ Parse configuration
  ❯ Generate outputs
    ❯ Generate src/graphql/generated/graphql.ts
      ✖ Load GraphQL schemas
        → Failed to load schema
        Load GraphQL documents
        Generate


 Found 1 error

  ✖ src/graphql/generated/graphql.ts
    Failed to load schema from http://localhost:8001/:

        request to http://localhost:8001/ failed, reason: connect ECONNR
EFUSED 127.0.0.1:8001
        FetchError: request to http://localhost:8001/ failed, reason: co
nnect ECONNREFUSED 127.0.0.1:8001
    at ClientRequest.<anonymous> (/workspace/node_modules/node-fetch/lib
/index.js:1491:11)
    at ClientRequest.emit (node:events:390:28)
    at Socket.socketErrorListener (node:_http_client:447:9)
    at Socket.emit (node:events:390:28)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:2
1)

        GraphQL Code Generator supports:
          - ES Modules and CommonJS exports (export as default or named 
export "schema")
          - Introspection JSON File
          - URL of GraphQL endpoint
          - Multiple files with type definitions (glob expression)
          - String in config file

        Try to use one of above options and run codegen again.
    Error: Failed to load schema
        at loadSchema (/workspace/node_modules/@graphql-codegen/cli/bin.
js:495:15)
        at processTicksAndRejections (node:internal/process/task_queues:
96:5)
        at async /workspace/node_modules/@graphql-codegen/cli/bin.js:907
:55
        at async Task.task (/workspace/node_modules/@graphql-codegen/cli
/bin.js:761:17)
    Error: Failed to load schema
        at loadSchema (/workspace/node_modules/@graphql-codegen/cli/bin.
js:495:15)
        at processTicksAndRejections (node:internal/process/task_queues:
96:5)
        at async /workspace/node_modules/@graphql-codegen/cli/bin.js:907
:55
        at async Task.task (/workspace/node_modules/@graphql-codegen/cli
/bin.js:761:17)


Something went wrong
```

**Environment:**

- OS: Containerized debian installed in Artix Linux.
- Codegen versions
    "@graphql-codegen/cli": "^1.9.0",
    "@graphql-codegen/typescript": "^2.4.3",
    "@graphql-codegen/typescript-operations": "^2.2.4",
    "@graphql-codegen/typescript-urql": "^3.5.1",
    "@graphql-codegen/urql-introspection": "^2.1.1",
    "@graphql-codegen/urql-svelte-operations-store": "^1.1.10",
- Node version: v16.13.2

UPDATE: apparently this happens due to my containerized app. If I run the command in my local repo instead of inside my container it works just fine. Might need a workaround for this

**Comment by ardatan** [comment]
Have you tried 0.0.0.0:8001 instead of localhost and are you sure you can access that URL in the browser?

**Comment by Lucasmiguelmac** [comment]
> Have you tried 0.0.0.0:8001 instead of localhost and are you sure you can access that URL in the browser?

See the update I just published in the initial comment I made. My backend does work. The problem is that I'm executing the codegen script from inside my container.

It's funny because Apollo queries worked just fine, but it seems to try to acess my container's port 8000 instead of my PC's. Otherwise I wouldn't be able to succesfully execute the codegen in my local environment.

Will be working on this and giving a fix if I find one.

**Comment by ardatan** [comment]
>  apparently this happens due to my containerized app. If I run the command in my local repo instead of inside my container it works just fine. Might need a workaround for this

That's why I asked you to try 0.0.0.0 instead of localhost. If still doesn't work, we need a reproduction.

**Comment by Lucasmiguelmac** [comment]
> 0.0.0.0

I don't understand what would this change. But this `codegen.yml` does not work either inside my container is that is what you are asking:
```yml
overwrite: true
schema: "http://0.0.0.0:8001/graphql/"
documents: "src/**/**/*.graphql"
config:
  withHooks: false
generates:
  src/graphql/generated/graphql.ts:
    plugins:
      - "typescript"
      - "typescript-operations"
      - "typescript-urql"
      - "urql-svelte-operations-store"
```

If you want to try reproduce this, here I made you a branch for the repo I'm working in: https://github.com/BitterWorks/svelte-flow-test/tree/codegen-error-reproduction

If you want to reproduce it you can either:
a) Start if from vscode devcontainer's extension
 b) run `docker-compose up` and run the `npm run generate` command inside the frontend container

**Comment by ardatan** [comment]
I'll take a look at the reproduction but in the meanwhile could you make sure that URL is accessible with cURL inside the container?

**Comment by Lucasmiguelmac** [comment]
> I'll take a look at the reproduction but in the meanwhile could you make sure that URL is accessible with cURL inside the container?

It did not work unfortunately. Got the following error:
![image](https://user-images.githubusercontent.com/49038881/152708903-03899113-9d7d-4b5e-a437-e9b1a338e0a0.png)

**Comment by ardatan** [comment]
It seems there is an issue in the container then or am I missing something?

**Comment by Lucasmiguelmac** [comment]
> 

Yes, it seems to be a container-related thing. I'll continue close the issue and try set up the networking. I might reopen it if the doubtious case that it is something else happens. Thank you very much

**Comment by akoskm** [comment]
> Have you tried 0.0.0.0:8001 instead of localhost and are you sure you can access that URL in the browser?

I had this exact same problem with a Strapi backend and using `0.0.0.0:1337` instead of `localhost:1337` worked for me!
