### ISSUE TITLE
`client-preset` doesn't take into account `namingConvention` 

### ISSUE THREAD

**Issue by Hugodby** [dotansimha/graphql-code-generator#8435]
### Describe the bug

When using the `client-preset`, if I add `namingConvention` config it won't be taken into account in the "types". It is however applied to the "documents".

### Your Example Website or App

Not public

### Steps to Reproduce the Bug or Issue

1. Use the following config:
Config used to reproduce
```
import type { CodegenConfig } from '@graphql-codegen/cli';

const config: CodegenConfig = {
  overwrite: true,
  schema: 'http://localhost:8080/api/graphql',
  documents: ['src/**/*.{ts,tsx}', '!src/gql/**/*'],
  generates: {
    'src/gql': {
      preset: 'client',
      plugins: [],
    },
  },
  config: { namingConvention: 'change-case-all#upperCase' },
};

export default config;

```
2. Run the codegen
3. Types case doesn't match the config in `src/gql/graphql`

### Expected behavior

`namingConvention` should be taken into account

### Platform

- OS: all
- NodeJS: v14
- `graphql` version: 16.6.0
- "@graphql-codegen/cli": "2.13.2",
- "@graphql-codegen/client-preset": "1.0.2",

### Codegen Config File

```
{
  overwrite: true,
  schema: 'http://localhost:8080/api/graphql',
  documents: ['src/**/*.{ts,tsx}', '!src/gql/**/*'],
  generates: {
    'src/gql': {
      preset: 'client',
      plugins: [],
    },
  },
  config: { namingConvention: 'change-case-all#upperCase' },
}
```

### Additional context

It seems to be because `options.config` isn't passed down here: https://github.com/dotansimha/graphql-code-generator/blob/f3c5b7a0044a0618898676ee6ee06f2494ac0b7c/packages/presets/client/src/index.ts#L177

**Comment by charlypoly** [comment]
Answered on the proposed PR: 
https://github.com/dotansimha/graphql-code-generator/pull/8436#issuecomment-1268125626

**Comment by charlypoly** [comment]
Hi @Hugodby,

it has been fixed in `@graphql-codegen/client-preset@1.0.4` 📦

**Comment by Hugodby** [comment]
Hi @charlypoly , thank you very much for working on this!

There is a small issue with the PR you wrote so this isn't completely fixed (see [comment](https://github.com/dotansimha/graphql-code-generator/pull/8455/files#r989223267)).

> Hi @Hugodby,
> 
> it has been fixed in `@graphql-codegen/client-preset@1.0.4` 📦

Hi @charlypoly , thank you very much for working on this!

There is a small issue with the PR you wrote so this isn't completely fixed (see [comment](https://github.com/dotansimha/graphql-code-generator/pull/8455/files#r989223267)).

**Comment by charlypoly** [comment]
@Hugodby, good catch, fixed in `@graphql-codegen/client-preset@1.0.5` 📦

**Comment by Hugodby** [comment]
You are so fast thank you! I just tested and it works now!
